/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => main_default
});
module.exports = __toCommonJS(main_exports);

// src/plugin.ts
var import_obsidian5 = require("obsidian");

// src/file-categories.ts
var FILE_CATEGORIES = [
  {
    id: "image",
    nameKey: "categoryImage",
    replacement: "image",
    extensions: ["png", "jpg", "jpeg", "gif", "webp", "svg", "heic", "bmp", "tiff"]
  },
  {
    id: "video",
    nameKey: "categoryVideo",
    replacement: "video",
    extensions: ["mp4", "mov", "avi", "mkv", "webm", "flv"]
  },
  {
    id: "audio",
    nameKey: "categoryAudio",
    replacement: "audio",
    extensions: ["mp3", "m4a", "wav", "flac", "ogg", "aac"]
  },
  {
    id: "document",
    nameKey: "categoryDocument",
    replacement: "markdown",
    extensions: ["pdf", "doc", "docx", "xls", "xlsx", "ppt", "pptx", "epub", "txt", "csv"]
  }
];
function getCategoryForExt(ext) {
  const normalized = ext.toLowerCase();
  return FILE_CATEGORIES.find((cat) => cat.extensions.includes(normalized));
}

// src/settings.ts
var DEFAULT_S3 = {
  provider: "r2",
  endpoint: "",
  region: "auto",
  bucketName: "",
  accessKeyId: "",
  secretAccessKey: "",
  customDomainName: "",
  pathTemplate: "attachments/{ext}/{hash2}/{hash}.{ext}"
};
var DEFAULT_ENABLED_EXTS = [
  "pdf",
  "mp3",
  "m4a",
  "wav",
  "mp4",
  "mov",
  "epub"
];
var DEFAULT_MIN_SIZE = {
  pdf: 1,
  mp3: 10,
  m4a: 10,
  wav: 10,
  mp4: 0,
  mov: 0,
  epub: 10
};
var DEFAULT_AUTO_CANDIDATE_EXTS = [
  "pdf",
  "mp3",
  "m4a",
  "wav",
  "mp4",
  "mov",
  "epub"
];
var DEFAULT_SETTINGS = {
  enabled: true,
  autoScanEnabled: false,
  scanIntervalMinutes: 30,
  quietSeconds: 600,
  autoScanMinSizeMiB: 0,
  attachmentRoot: "99 Attachments",
  deletePolicy: "confirm",
  autoDeleteDelayHours: 24,
  s3: DEFAULT_S3,
  enabledExtensions: DEFAULT_ENABLED_EXTS,
  minSizeRules: DEFAULT_MIN_SIZE,
  autoCandidateExts: DEFAULT_AUTO_CANDIDATE_EXTS,
  customExtensions: [],
  customReplacements: {},
  pendingDeletes: [],
  logs: []
};
function isObject(value) {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}
function migrateOldSettings(loaded) {
  const result = {};
  if (loaded.r2) {
    result.s3 = {
      ...DEFAULT_S3,
      ...loaded.r2,
      provider: "r2",
      region: "auto"
    };
  }
  if (Array.isArray(loaded.rules) && loaded.rules.length > 0) {
    const enabledExtensions = [];
    const minSizeRules = {};
    const autoCandidateExts = [];
    const customReplacements = {};
    for (const rule of loaded.rules) {
      const exts = rule.extensions.split(",").map((e) => e.trim().toLowerCase()).filter(Boolean);
      for (const ext of exts) {
        enabledExtensions.push(ext);
        minSizeRules[ext] = rule.minSizeMiB;
        if (rule.autoCandidate)
          autoCandidateExts.push(ext);
        if (rule.replacement !== FILE_CATEGORIES.find((c) => c.extensions.includes(ext))?.replacement) {
          customReplacements[ext] = rule.replacement;
        }
      }
    }
    result.enabledExtensions = enabledExtensions;
    result.minSizeRules = minSizeRules;
    result.autoCandidateExts = autoCandidateExts;
    result.customReplacements = customReplacements;
  }
  return result;
}
function mergeSettings(defaults, loaded) {
  const data = isObject(loaded) ? loaded : {};
  const migrated = migrateOldSettings(data);
  const s3Data = data.s3 || migrated.s3 || data.r2 || {};
  const s3 = {
    ...defaults.s3,
    ...s3Data,
    provider: s3Data.provider || (data.r2 ? "r2" : "r2"),
    region: s3Data.region || (s3Data.provider === "r2" || data.r2 ? "auto" : "us-east-1")
  };
  return {
    ...defaults,
    s3,
    enabledExtensions: migrated.enabledExtensions || data.enabledExtensions || defaults.enabledExtensions,
    minSizeRules: migrated.minSizeRules || data.minSizeRules || defaults.minSizeRules,
    autoCandidateExts: migrated.autoCandidateExts || data.autoCandidateExts || defaults.autoCandidateExts,
    customExtensions: data.customExtensions || defaults.customExtensions,
    customReplacements: migrated.customReplacements || data.customReplacements || defaults.customReplacements,
    pendingDeletes: Array.isArray(data.pendingDeletes) ? data.pendingDeletes : [],
    logs: Array.isArray(data.logs) ? data.logs.slice(0, 100) : []
  };
}
function getReplacementForExt(ext, settings) {
  if (settings.customReplacements[ext])
    return settings.customReplacements[ext];
  const allExts = [...FILE_CATEGORIES.flatMap((c) => c.extensions), ...settings.customExtensions];
  if (!allExts.includes(ext) && !settings.enabledExtensions.includes(ext))
    return "markdown";
  const category = FILE_CATEGORIES.find((c) => c.extensions.includes(ext));
  return category?.replacement || "markdown";
}

// src/link-parser.ts
function splitFragment(path) {
  const hashIndex = path.indexOf("#");
  if (hashIndex === -1)
    return { path, fragment: "" };
  return { path: path.slice(0, hashIndex), fragment: path.slice(hashIndex + 1) };
}
function decodeLinkPath(path) {
  try {
    return decodeURIComponent(path);
  } catch {
    return path;
  }
}
function basename(path) {
  return String(path || "").split("/").pop() || path;
}
function findCodeRegions(text) {
  const regions = [];
  const fenced = /^(`{3,}|~{3,}).*?\n[\s\S]*?^\1/gm;
  let m;
  while ((m = fenced.exec(text)) !== null) {
    regions.push([m.index, m.index + m[0].length]);
  }
  const inline = /(`+)([\s\S]+?)\1/g;
  while ((m = inline.exec(text)) !== null) {
    regions.push([m.index, m.index + m[0].length]);
  }
  return regions;
}
function isInCodeRegion(pos, regions) {
  for (const [start, end] of regions) {
    if (pos >= start && pos < end)
      return true;
  }
  return false;
}
function extractLocalRefs(text) {
  const refs = [];
  const codeRegions = findCodeRegions(text);
  const wiki = /!?\[\[([^\]\n]+?)\]\]/g;
  let match;
  while ((match = wiki.exec(text)) !== null) {
    if (isInCodeRegion(match.index, codeRegions))
      continue;
    const raw = match[0];
    const inner = match[1];
    const pipeIndex = inner.indexOf("|");
    const targetPart = pipeIndex >= 0 ? inner.slice(0, pipeIndex) : inner;
    const alias = pipeIndex >= 0 ? inner.slice(pipeIndex + 1) : "";
    const parsed = splitFragment(targetPart.trim());
    refs.push({
      kind: raw.startsWith("!") ? "wiki-embed" : "wiki",
      raw,
      start: match.index,
      end: match.index + raw.length,
      target: parsed.path,
      fragment: parsed.fragment,
      label: alias || basename(parsed.path)
    });
  }
  const markdown = /!?\[([^\]\n]*)\]\(([^)\n]+)\)/g;
  while ((match = markdown.exec(text)) !== null) {
    if (isInCodeRegion(match.index, codeRegions))
      continue;
    const raw = match[0];
    let href = match[2].trim();
    if (href.startsWith("<") && href.endsWith(">"))
      href = href.slice(1, -1);
    if (/^(https?:|mailto:|obsidian:|#)/i.test(href))
      continue;
    const parsed = splitFragment(decodeLinkPath(href));
    refs.push({
      kind: raw.startsWith("!") ? "markdown-embed" : "markdown",
      raw,
      start: match.index,
      end: match.index + raw.length,
      target: parsed.path,
      fragment: parsed.fragment,
      label: match[1] || basename(parsed.path)
    });
  }
  return refs.sort((a, b) => a.start - b.start);
}

// src/s3-client.ts
var import_obsidian = require("obsidian");

// src/crypto.ts
function bufferToHex(buffer) {
  return Array.from(new Uint8Array(buffer)).map((b) => b.toString(16).padStart(2, "0")).join("");
}
async function sha256Hex(data) {
  const hash = await crypto.subtle.digest("SHA-256", data);
  return bufferToHex(hash);
}
async function hmacSha256(key, data) {
  const cryptoKey = await crypto.subtle.importKey(
    "raw",
    key,
    { name: "HMAC", hash: "SHA-256" },
    false,
    ["sign"]
  );
  return crypto.subtle.sign("HMAC", cryptoKey, new TextEncoder().encode(data));
}
async function hmacSha256Hex(key, data) {
  return bufferToHex(await hmacSha256(key, data));
}
async function getSignatureKey(secret, dateStamp, region, service) {
  const enc = new TextEncoder();
  const kDate = await hmacSha256(enc.encode(`AWS4${secret}`), dateStamp);
  const kRegion = await hmacSha256(kDate, region);
  const kService = await hmacSha256(kRegion, service);
  return hmacSha256(kService, "aws4_request");
}

// src/utils.ts
function basename2(path) {
  return String(path || "").split("/").pop() || path;
}
function trimSlashes(path) {
  return String(path || "").replace(/^\/+|\/+$/g, "");
}
function safeFilename(name) {
  return String(name || "attachment").replace(/[\\/:*?"<>|#%]+/g, "-");
}
function renderPathTemplate(template, values) {
  return String(template || "attachments/{ext}/{hash2}/{hash}.{ext}").replace(/\{ext\}/g, values.ext).replace(/\{hash\}/g, values.hash).replace(/\{hash2\}/g, values.hash2).replace(/\{filename\}/g, values.filename).replace(/^\/+/, "");
}
function buildPublicUrl(domain, key) {
  let cleanDomain = String(domain || "").replace(/\/+$/, "");
  if (cleanDomain && !/^[a-zA-Z][a-zA-Z0-9+.-]*:\/\//.test(cleanDomain)) {
    cleanDomain = `https://${cleanDomain}`;
  }
  return `${cleanDomain}/${key.split("/").map(encodeURIComponent).join("/")}`;
}
function replaceAllLiteral(text, search, replacement) {
  return text.split(search).join(replacement);
}
function escapeMarkdownLabel(label) {
  return String(label || "attachment").replace(/\]/g, "\\]");
}
function formatBytes(bytes) {
  if (bytes >= 1024 * 1024 * 1024)
    return `${(bytes / 1024 / 1024 / 1024).toFixed(2)} GiB`;
  if (bytes >= 1024 * 1024)
    return `${(bytes / 1024 / 1024).toFixed(2)} MiB`;
  if (bytes >= 1024)
    return `${(bytes / 1024).toFixed(1)} KiB`;
  return `${bytes} B`;
}
function contentTypeForExt(ext) {
  const map = {
    pdf: "application/pdf",
    epub: "application/epub+zip",
    doc: "application/msword",
    docx: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    xls: "application/vnd.ms-excel",
    xlsx: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    ppt: "application/vnd.ms-powerpoint",
    pptx: "application/vnd.openxmlformats-officedocument.presentationml.presentation",
    txt: "text/plain",
    csv: "text/csv",
    png: "image/png",
    jpg: "image/jpeg",
    jpeg: "image/jpeg",
    gif: "image/gif",
    webp: "image/webp",
    svg: "image/svg+xml",
    heic: "image/heic",
    bmp: "image/bmp",
    tiff: "image/tiff",
    mp3: "audio/mpeg",
    m4a: "audio/mp4",
    wav: "audio/wav",
    flac: "audio/flac",
    ogg: "audio/ogg",
    aac: "audio/aac",
    mp4: "video/mp4",
    mov: "video/quicktime",
    avi: "video/x-msvideo",
    mkv: "video/x-matroska",
    webm: "video/webm",
    flv: "video/x-flv"
  };
  return map[ext] || "application/octet-stream";
}
function isPreviewableImage(ext) {
  return ["png", "jpg", "jpeg", "gif", "webp", "svg", "bmp"].includes(
    String(ext || "").toLowerCase()
  );
}
function toAmzDate(date) {
  return date.toISOString().replace(/[:-]|\.\d{3}/g, "");
}
function debounce(fn, ms) {
  let timer;
  return (...args) => {
    window.clearTimeout(timer);
    timer = window.setTimeout(() => fn(...args), ms);
  };
}

// src/s3-client.ts
var MAX_RETRIES = 3;
var BASE_DELAY_MS = 1e3;
function sleep(ms) {
  return new Promise((resolve) => window.setTimeout(resolve, ms));
}
function shouldRetry(status) {
  return status === 429 || status >= 500;
}
async function putS3Object(config, key, body, contentType, formatError, precomputedHash) {
  const endpoint = String(config.endpoint || "").replace(/\/+$/, "");
  const bucket = config.bucketName;
  const encodedKey = key.split("/").map(encodeURIComponent).join("/");
  const url = `${endpoint}/${bucket}/${encodedKey}`;
  const parsed = new URL(url);
  const region = config.region || "auto";
  for (let attempt = 0; attempt <= MAX_RETRIES; attempt++) {
    const now = /* @__PURE__ */ new Date();
    const amzDate = toAmzDate(now);
    const dateStamp = amzDate.slice(0, 8);
    const payloadHash = precomputedHash || await sha256Hex(body);
    const canonicalHeaders = [
      `host:${parsed.host}`,
      `x-amz-content-sha256:${payloadHash}`,
      `x-amz-date:${amzDate}`
    ].join("\n") + "\n";
    const signedHeaders = "host;x-amz-content-sha256;x-amz-date";
    const canonicalRequest = [
      "PUT",
      parsed.pathname,
      "",
      canonicalHeaders,
      signedHeaders,
      payloadHash
    ].join("\n");
    const credentialScope = `${dateStamp}/${region}/s3/aws4_request`;
    const canonicalRequestHash = await sha256Hex(new TextEncoder().encode(canonicalRequest));
    const stringToSign = [
      "AWS4-HMAC-SHA256",
      amzDate,
      credentialScope,
      canonicalRequestHash
    ].join("\n");
    const signingKey = await getSignatureKey(
      config.secretAccessKey,
      dateStamp,
      region,
      "s3"
    );
    const signature = await hmacSha256Hex(signingKey, stringToSign);
    const headers = {
      "Content-Type": contentType,
      "x-amz-content-sha256": payloadHash,
      "x-amz-date": amzDate,
      Authorization: `AWS4-HMAC-SHA256 Credential=${config.accessKeyId}/${credentialScope}, SignedHeaders=${signedHeaders}, Signature=${signature}`
    };
    try {
      const response = await (0, import_obsidian.requestUrl)({
        url,
        method: "PUT",
        headers,
        body: body.buffer.slice(body.byteOffset, body.byteOffset + body.byteLength),
        throw: false
      });
      if (response.status >= 200 && response.status < 300)
        return;
      if (shouldRetry(response.status) && attempt < MAX_RETRIES) {
        await sleep(BASE_DELAY_MS * Math.pow(2, attempt));
        continue;
      }
      throw new Error(formatError(response.status, response.text || ""));
    } catch (error) {
      if (error instanceof Error && error.message) {
        if (attempt >= MAX_RETRIES)
          throw error;
      }
      if (attempt < MAX_RETRIES) {
        await sleep(BASE_DELAY_MS * Math.pow(2, attempt));
        continue;
      }
      throw error;
    }
  }
}
async function deleteS3Object(config, key) {
  const endpoint = String(config.endpoint || "").replace(/\/+$/, "");
  const bucket = config.bucketName;
  const encodedKey = key.split("/").map(encodeURIComponent).join("/");
  const url = `${endpoint}/${bucket}/${encodedKey}`;
  const parsed = new URL(url);
  const region = config.region || "auto";
  const now = /* @__PURE__ */ new Date();
  const amzDate = toAmzDate(now);
  const dateStamp = amzDate.slice(0, 8);
  const emptyHash = await sha256Hex(new Uint8Array(0));
  const canonicalHeaders = [
    `host:${parsed.host}`,
    `x-amz-content-sha256:${emptyHash}`,
    `x-amz-date:${amzDate}`
  ].join("\n") + "\n";
  const signedHeaders = "host;x-amz-content-sha256;x-amz-date";
  const canonicalRequest = [
    "DELETE",
    parsed.pathname,
    "",
    canonicalHeaders,
    signedHeaders,
    emptyHash
  ].join("\n");
  const credentialScope = `${dateStamp}/${region}/s3/aws4_request`;
  const canonicalRequestHash = await sha256Hex(new TextEncoder().encode(canonicalRequest));
  const stringToSign = [
    "AWS4-HMAC-SHA256",
    amzDate,
    credentialScope,
    canonicalRequestHash
  ].join("\n");
  const signingKey = await getSignatureKey(config.secretAccessKey, dateStamp, region, "s3");
  const signature = await hmacSha256Hex(signingKey, stringToSign);
  const headers = {
    "x-amz-content-sha256": emptyHash,
    "x-amz-date": amzDate,
    Authorization: `AWS4-HMAC-SHA256 Credential=${config.accessKeyId}/${credentialScope}, SignedHeaders=${signedHeaders}, Signature=${signature}`
  };
  const response = await (0, import_obsidian.requestUrl)({ url, method: "DELETE", headers, throw: false });
  if (response.status >= 400 && response.status !== 404) {
    console.warn(`S3 delete failed for key "${key}" (${response.status}): ${response.text || ""}`);
  }
}
async function testS3Connection(config) {
  const endpoint = String(config.endpoint || "").replace(/\/+$/, "");
  const bucket = config.bucketName;
  const url = `${endpoint}/${bucket}/`;
  const parsed = new URL(url);
  const region = config.region || "auto";
  const now = /* @__PURE__ */ new Date();
  const amzDate = toAmzDate(now);
  const dateStamp = amzDate.slice(0, 8);
  const emptyHash = await sha256Hex(new Uint8Array(0));
  const canonicalHeaders = [
    `host:${parsed.host}`,
    `x-amz-content-sha256:${emptyHash}`,
    `x-amz-date:${amzDate}`
  ].join("\n") + "\n";
  const signedHeaders = "host;x-amz-content-sha256;x-amz-date";
  const canonicalRequest = [
    "GET",
    parsed.pathname,
    "",
    canonicalHeaders,
    signedHeaders,
    emptyHash
  ].join("\n");
  const credentialScope = `${dateStamp}/${region}/s3/aws4_request`;
  const canonicalRequestHash = await sha256Hex(new TextEncoder().encode(canonicalRequest));
  const stringToSign = [
    "AWS4-HMAC-SHA256",
    amzDate,
    credentialScope,
    canonicalRequestHash
  ].join("\n");
  const signingKey = await getSignatureKey(config.secretAccessKey, dateStamp, region, "s3");
  const signature = await hmacSha256Hex(signingKey, stringToSign);
  const headers = {
    "x-amz-content-sha256": emptyHash,
    "x-amz-date": amzDate,
    Authorization: `AWS4-HMAC-SHA256 Credential=${config.accessKeyId}/${credentialScope}, SignedHeaders=${signedHeaders}, Signature=${signature}`
  };
  const response = await (0, import_obsidian.requestUrl)({ url, method: "GET", headers, throw: false });
  if (response.status >= 200 && response.status < 400)
    return;
  throw new Error(`S3 connection test failed (${response.status}): ${response.text || "Unknown error"}`);
}

// src/i18n.ts
var I18N = {
  en: {
    // Ribbon & Commands
    ribbonScan: "Scan current note attachments",
    commandScanCurrent: "Scan current note attachments",
    commandScanVault: "Scan vault candidates without replacing",
    commandProcessDeletes: "Process delayed attachment deletes",
    // Notices
    disabled: "Attachment Imagebed Manager is disabled.",
    openMarkdownFirst: "Open a Markdown note first.",
    noCandidates: "No eligible local attachments found in this note.",
    autoScanFailed: "Attachment auto scan failed: {error}",
    delayedDeleteFailed: "Attachment Imagebed Manager delayed delete failed",
    autoScanReplaced: "Attachment auto scan replaced {count} link(s).",
    noteChanged: "Note changed during upload; skipped replacement.",
    originalLinkChanged: "Original link changed before write: {link}",
    missingS3: "Missing S3 settings: {settings}",
    uploadFailed: "S3 upload failed ({status}): {text}",
    // Candidate Modal
    replaceTitle: "Replace note attachments",
    candidateSummary: "Found {count} local attachment(s) in this note that can be uploaded.",
    referenceCount: "{count} ref(s)",
    cancel: "Cancel",
    uploadReplace: "Upload & Replace",
    noSelected: "No attachment selected.",
    replacedNotice: "Replaced {count} link(s) successfully!",
    replaceFailed: "Attachment replacement failed: {error}",
    uploadingTitle: "Uploading attachments",
    preparing: "Preparing {count} selected attachment(s)...",
    starting: "Starting...",
    phaseUploading: "Uploading",
    phaseUploaded: "Uploaded",
    phaseRewriting: "Rewriting note",
    phaseTrashing: "Moving local files to trash",
    phaseScheduling: "Scheduling delayed delete",
    phaseDone: "Done!",
    linksReplacedTitle: "Links replaced successfully!",
    linksReplacedDesc: "Local links have been replaced with remote URLs. Do you want to delete the original local files?",
    keepLocal: "Keep local files",
    deleteLocal: "Delete local files",
    movedToTrash: "Moved {count} local file(s) to trash.",
    localDeleteFailed: "Local delete failed: {error}",
    close: "Close",
    viewList: "List",
    viewGallery: "Gallery",
    filterAll: "All",
    filterOther: "Other",
    selectAll: "Select all",
    // Dry Run Modal
    vaultScanTitle: "Vault scan result",
    vaultScanFound: "Found {count} attachment(s) that would be auto-uploaded.",
    scanningVault: "Scanning vault... ({current}/{total})",
    // Settings - Status
    settingsTitle: "Attachment Imagebed Manager",
    setupComplete: "S3 storage is configured and ready to use.",
    setupIncomplete: "S3 storage is not configured yet. Fill in the settings below to get started.",
    // Settings - S3
    s3Storage: "Step 1: Connect your cloud storage",
    s3SetupGuide: "Choose a storage provider and fill in the credentials. Your files will be uploaded here and accessed via the public domain.",
    provider: "Storage provider",
    providerDesc: "Cloudflare R2 is recommended \u2014 free egress, generous free tier.",
    region: "Region",
    regionDesc: "e.g. us-east-1, ap-southeast-1",
    providerR2: "Cloudflare R2 (recommended)",
    providerS3: "AWS S3",
    providerMinio: "MinIO",
    providerCustom: "Custom S3",
    endpoint: "Endpoint URL",
    endpointDesc: "e.g. https://abc123.r2.cloudflarestorage.com",
    bucketName: "Bucket name",
    bucketNameDesc: "The bucket you created in your storage provider.",
    accessKeyId: "Access Key ID",
    accessKeyIdDesc: "Found in your storage provider's API settings.",
    secretAccessKey: "Secret Access Key",
    publicDomain: "Public access URL",
    publicDomainDesc: "The URL prefix for accessing uploaded files, e.g. https://pub-xxx.r2.dev",
    objectPathTemplate: "Upload path template",
    pathTemplateDesc: "Variables: {ext} = extension, {hash} = file hash, {hash2} = first 2 chars of hash, {filename} = original name. Default works for most cases.",
    testConnection: "Test connection",
    testConnectionDesc: "Click to verify your credentials are correct.",
    testing: "Testing...",
    testConnectionSuccess: "Connection test passed!",
    testConnectionFailed: "Connection test failed: {error}",
    // Settings - General
    generalSettings: "Step 2: General settings",
    pluginEnabled: "Enable plugin",
    pluginEnabledDesc: "Turn on/off the scanning and replacement features.",
    mobileHint: "Note: Scheduled auto-scan and delayed delete are disabled on mobile devices. Manual upload and replacement work normally.",
    attachmentRoot: "Attachment folder",
    attachmentRootDesc: "Only files under this folder will be processed. Default: 99 Attachments",
    deletePolicy: "After replacing links, delete local files?",
    deletePolicyDesc: "Choose what happens to the original local files after they are replaced with remote URLs.",
    deleteConfirm: "Ask me each time (recommended)",
    deleteImmediate: "Delete immediately after replacement",
    deleteDelayed: "Delete after a delay",
    deleteDelayHours: "Delay before delete (hours)",
    deleteDelayHoursDesc: "Files will be moved to trash after this many hours.",
    automaticScan: "Auto-scan vault periodically",
    automaticScanDesc: "Automatically find and replace eligible attachments in the background.",
    scanInterval: "Scan interval (minutes)",
    scanIntervalDesc: "How often to scan the vault. Default: 30",
    quietSeconds: "Skip recently modified files (seconds)",
    quietSecondsDesc: "Files modified within this time are skipped by auto-scan. Default: 600 (10 min)",
    autoScanMinSize: "Auto-scan: ignore files smaller than (MiB)",
    autoScanMinSizeDesc: "Only applies to auto-scan. Manual scan is not affected. Set to 0 to upload all files.",
    // Settings - File Types
    fileTypes: "Step 3: Choose file types to upload",
    fileTypesDesc: "Click on a file type to toggle it. Checked types will be uploaded when scanning.",
    extCount: "{enabled}/{total} enabled",
    categoryImage: "Images",
    categoryVideo: "Videos",
    categoryAudio: "Audio",
    categoryDocument: "Documents",
    deselectAll: "Deselect all",
    customExtensions: "Custom file types",
    customExtPlaceholder: "e.g. sketch, fig, psd",
    addExtension: "Add",
    removeExtension: "Remove",
    minSizeSection: "Minimum file size filter (advanced)",
    minSizeSectionDesc: "Only upload files larger than the specified size. Set to 0 to upload all files.",
    minSizeMiB: "Min size (MiB)",
    autoCandidate: "Include in scheduled scan",
    autoScanShort: "Scheduled",
    advancedSettings: "Advanced settings",
    replacementType: "Replacement format",
    markdownLink: "Markdown link",
    imageEmbed: "Image embed",
    audioTag: "Audio tag",
    videoTag: "Video tag",
    // Settings - Log
    recentLog: "Recent activity",
    pendingDeletes: "Pending delayed deletes",
    noLogs: "No activity yet. Scan a note to get started."
  },
  zh: {
    // Ribbon & Commands
    ribbonScan: "\u626B\u63CF\u5F53\u524D\u6587\u6863\u9644\u4EF6",
    commandScanCurrent: "\u626B\u63CF\u5F53\u524D\u6587\u6863\u9644\u4EF6",
    commandScanVault: "\u626B\u63CF\u5168\u5E93\u5019\u9009\u4F46\u4E0D\u66FF\u6362",
    commandProcessDeletes: "\u5904\u7406\u5EF6\u8FDF\u5220\u9664\u9644\u4EF6",
    // Notices
    disabled: "\u9644\u4EF6\u56FE\u5E8A\u7BA1\u7406\u5668\u5DF2\u505C\u7528\u3002",
    openMarkdownFirst: "\u8BF7\u5148\u6253\u5F00\u4E00\u4E2A Markdown \u6587\u6863\u3002",
    noCandidates: "\u5F53\u524D\u6587\u6863\u6CA1\u6709\u53EF\u4E0A\u4F20\u66FF\u6362\u7684\u672C\u5730\u9644\u4EF6\u3002",
    autoScanFailed: "\u9644\u4EF6\u81EA\u52A8\u626B\u63CF\u5931\u8D25\uFF1A{error}",
    delayedDeleteFailed: "\u9644\u4EF6\u56FE\u5E8A\u7BA1\u7406\u5668\u5EF6\u8FDF\u5220\u9664\u5931\u8D25",
    autoScanReplaced: "\u9644\u4EF6\u81EA\u52A8\u626B\u63CF\u5DF2\u66FF\u6362 {count} \u4E2A\u94FE\u63A5\u3002",
    noteChanged: "\u4E0A\u4F20\u671F\u95F4\u6587\u6863\u53D1\u751F\u53D8\u5316\uFF0C\u5DF2\u8DF3\u8FC7\u66FF\u6362\u3002",
    originalLinkChanged: "\u539F\u59CB\u94FE\u63A5\u5728\u5199\u5165\u524D\u53D1\u751F\u53D8\u5316\uFF1A{link}",
    missingS3: "\u7F3A\u5C11 S3 \u914D\u7F6E\uFF1A{settings}",
    uploadFailed: "S3 \u4E0A\u4F20\u5931\u8D25\uFF08{status}\uFF09\uFF1A{text}",
    // Candidate Modal
    replaceTitle: "\u66FF\u6362\u6587\u6863\u9644\u4EF6",
    candidateSummary: "\u5728\u5F53\u524D\u6587\u6863\u4E2D\u627E\u5230 {count} \u4E2A\u53EF\u4E0A\u4F20\u66FF\u6362\u7684\u672C\u5730\u9644\u4EF6\u3002",
    referenceCount: "{count} \u5904\u5F15\u7528",
    cancel: "\u53D6\u6D88",
    uploadReplace: "\u4E0A\u4F20\u5E76\u66FF\u6362",
    noSelected: "\u6CA1\u6709\u9009\u62E9\u9644\u4EF6\u3002",
    replacedNotice: "\u5DF2\u6210\u529F\u66FF\u6362 {count} \u4E2A\u94FE\u63A5\uFF01",
    replaceFailed: "\u9644\u4EF6\u66FF\u6362\u5931\u8D25\uFF1A{error}",
    uploadingTitle: "\u6B63\u5728\u4E0A\u4F20\u9644\u4EF6",
    preparing: "\u51C6\u5907\u4E0A\u4F20 {count} \u4E2A\u5DF2\u9009\u62E9\u9644\u4EF6...",
    starting: "\u6B63\u5728\u5F00\u59CB...",
    phaseUploading: "\u6B63\u5728\u4E0A\u4F20",
    phaseUploaded: "\u5DF2\u4E0A\u4F20",
    phaseRewriting: "\u6B63\u5728\u6539\u5199\u6587\u6863",
    phaseTrashing: "\u6B63\u5728\u79FB\u52A8\u672C\u5730\u6587\u4EF6\u5230\u56DE\u6536\u7AD9",
    phaseScheduling: "\u6B63\u5728\u52A0\u5165\u5EF6\u8FDF\u5220\u9664\u961F\u5217",
    phaseDone: "\u5B8C\u6210\uFF01",
    linksReplacedTitle: "\u94FE\u63A5\u66FF\u6362\u6210\u529F\uFF01",
    linksReplacedDesc: "\u672C\u5730\u94FE\u63A5\u5DF2\u66FF\u6362\u4E3A\u8FDC\u7A0B URL\u3002\u662F\u5426\u5220\u9664\u539F\u672C\u5730\u6587\u4EF6\uFF1F",
    keepLocal: "\u4FDD\u7559\u672C\u5730\u6587\u4EF6",
    deleteLocal: "\u5220\u9664\u672C\u5730\u6587\u4EF6",
    movedToTrash: "\u5DF2\u5C06 {count} \u4E2A\u672C\u5730\u6587\u4EF6\u79FB\u5165\u56DE\u6536\u7AD9\u3002",
    localDeleteFailed: "\u672C\u5730\u6587\u4EF6\u5220\u9664\u5931\u8D25\uFF1A{error}",
    close: "\u5173\u95ED",
    viewList: "\u5217\u8868",
    viewGallery: "\u753B\u5ECA",
    filterAll: "\u5168\u90E8",
    filterOther: "\u5176\u4ED6",
    selectAll: "\u5168\u9009",
    // Dry Run Modal
    vaultScanTitle: "\u5168\u5E93\u626B\u63CF\u7ED3\u679C",
    vaultScanFound: "\u627E\u5230 {count} \u4E2A\u53EF\u81EA\u52A8\u4E0A\u4F20\u7684\u9644\u4EF6\u3002",
    scanningVault: "\u6B63\u5728\u626B\u63CF\u5168\u5E93...\uFF08{current}/{total}\uFF09",
    // Settings - Status
    settingsTitle: "\u9644\u4EF6\u56FE\u5E8A\u7BA1\u7406\u5668",
    setupComplete: "S3 \u5B58\u50A8\u5DF2\u914D\u7F6E\uFF0C\u53EF\u4EE5\u6B63\u5E38\u4F7F\u7528\u3002",
    setupIncomplete: "S3 \u5B58\u50A8\u5C1A\u672A\u914D\u7F6E\uFF0C\u8BF7\u5148\u586B\u5199\u4E0B\u65B9\u8BBE\u7F6E\u3002",
    // Settings - S3
    s3Storage: "\u7B2C\u4E00\u6B65\uFF1A\u8FDE\u63A5\u4E91\u5B58\u50A8",
    s3SetupGuide: "\u9009\u62E9\u5B58\u50A8\u670D\u52A1\u5546\u5E76\u586B\u5199\u51ED\u636E\u3002\u9644\u4EF6\u5C06\u4E0A\u4F20\u5230\u8FD9\u91CC\uFF0C\u5E76\u901A\u8FC7\u516C\u5F00\u57DF\u540D\u8BBF\u95EE\u3002",
    provider: "\u5B58\u50A8\u670D\u52A1\u5546",
    providerDesc: "\u63A8\u8350\u4F7F\u7528 Cloudflare R2 \u2014 \u514D\u8D39\u51FA\u7AD9\u6D41\u91CF\uFF0C\u514D\u8D39\u989D\u5EA6\u5145\u8DB3\u3002",
    region: "\u533A\u57DF",
    regionDesc: "\u4F8B\u5982 us-east-1\u3001ap-southeast-1",
    providerR2: "Cloudflare R2\uFF08\u63A8\u8350\uFF09",
    providerS3: "AWS S3",
    providerMinio: "MinIO",
    providerCustom: "\u81EA\u5B9A\u4E49 S3",
    endpoint: "\u7AEF\u70B9 URL",
    endpointDesc: "\u4F8B\u5982 https://abc123.r2.cloudflarestorage.com",
    bucketName: "\u5B58\u50A8\u6876\u540D\u79F0",
    bucketNameDesc: "\u5728\u5B58\u50A8\u670D\u52A1\u5546\u4E2D\u521B\u5EFA\u7684\u5B58\u50A8\u6876\u3002",
    accessKeyId: "Access Key ID",
    accessKeyIdDesc: "\u5728\u5B58\u50A8\u670D\u52A1\u5546\u7684 API \u8BBE\u7F6E\u4E2D\u83B7\u53D6\u3002",
    secretAccessKey: "Secret Access Key",
    publicDomain: "\u516C\u5F00\u8BBF\u95EE URL",
    publicDomainDesc: "\u4E0A\u4F20\u6587\u4EF6\u7684\u8BBF\u95EE\u524D\u7F00\uFF0C\u4F8B\u5982 https://pub-xxx.r2.dev",
    objectPathTemplate: "\u4E0A\u4F20\u8DEF\u5F84\u6A21\u677F",
    pathTemplateDesc: "\u53EF\u7528\u53D8\u91CF\uFF1A{ext} = \u540E\u7F00\uFF0C{hash} = \u6587\u4EF6\u54C8\u5E0C\uFF0C{hash2} = \u54C8\u5E0C\u524D2\u4F4D\uFF0C{filename} = \u539F\u59CB\u6587\u4EF6\u540D\u3002\u9ED8\u8BA4\u503C\u9002\u7528\u4E8E\u5927\u591A\u6570\u60C5\u51B5\u3002",
    testConnection: "\u6D4B\u8BD5\u8FDE\u63A5",
    testConnectionDesc: "\u70B9\u51FB\u9A8C\u8BC1\u51ED\u636E\u662F\u5426\u6B63\u786E\u3002",
    testing: "\u6D4B\u8BD5\u4E2D...",
    testConnectionSuccess: "\u8FDE\u63A5\u6D4B\u8BD5\u901A\u8FC7\uFF01",
    testConnectionFailed: "\u8FDE\u63A5\u6D4B\u8BD5\u5931\u8D25\uFF1A{error}",
    // Settings - General
    generalSettings: "\u7B2C\u4E8C\u6B65\uFF1A\u57FA\u672C\u8BBE\u7F6E",
    pluginEnabled: "\u542F\u7528\u63D2\u4EF6",
    pluginEnabledDesc: "\u5F00\u542F\u6216\u5173\u95ED\u626B\u63CF\u548C\u66FF\u6362\u529F\u80FD\u3002",
    mobileHint: "\u63D0\u793A\uFF1A\u79FB\u52A8\u7AEF\u4E0D\u652F\u6301\u5B9A\u65F6\u81EA\u52A8\u626B\u63CF\u548C\u5EF6\u8FDF\u5220\u9664\u3002\u624B\u52A8\u4E0A\u4F20\u548C\u66FF\u6362\u529F\u80FD\u6B63\u5E38\u4F7F\u7528\u3002",
    attachmentRoot: "\u9644\u4EF6\u6587\u4EF6\u5939",
    attachmentRootDesc: "\u53EA\u5904\u7406\u6B64\u6587\u4EF6\u5939\u4E0B\u7684\u6587\u4EF6\u3002\u9ED8\u8BA4\uFF1A99 Attachments",
    deletePolicy: "\u66FF\u6362\u94FE\u63A5\u540E\uFF0C\u662F\u5426\u5220\u9664\u672C\u5730\u6587\u4EF6\uFF1F",
    deletePolicyDesc: "\u9009\u62E9\u66FF\u6362\u4E3A\u8FDC\u7A0B\u94FE\u63A5\u540E\uFF0C\u539F\u672C\u5730\u6587\u4EF6\u7684\u5904\u7406\u65B9\u5F0F\u3002",
    deleteConfirm: "\u6BCF\u6B21\u8BE2\u95EE\u6211\uFF08\u63A8\u8350\uFF09",
    deleteImmediate: "\u66FF\u6362\u540E\u7ACB\u5373\u5220\u9664",
    deleteDelayed: "\u5EF6\u8FDF\u5220\u9664",
    deleteDelayHours: "\u5EF6\u8FDF\u5220\u9664\u65F6\u95F4\uFF08\u5C0F\u65F6\uFF09",
    deleteDelayHoursDesc: "\u6587\u4EF6\u5C06\u5728\u6307\u5B9A\u5C0F\u65F6\u540E\u79FB\u5165\u56DE\u6536\u7AD9\u3002",
    automaticScan: "\u5B9A\u671F\u81EA\u52A8\u626B\u63CF\u5168\u5E93",
    automaticScanDesc: "\u81EA\u52A8\u5728\u540E\u53F0\u67E5\u627E\u5E76\u66FF\u6362\u7B26\u5408\u6761\u4EF6\u7684\u9644\u4EF6\u3002",
    scanInterval: "\u626B\u63CF\u95F4\u9694\uFF08\u5206\u949F\uFF09",
    scanIntervalDesc: "\u591A\u4E45\u626B\u63CF\u4E00\u6B21\u5168\u5E93\u3002\u9ED8\u8BA4\uFF1A30",
    quietSeconds: "\u8DF3\u8FC7\u6700\u8FD1\u4FEE\u6539\u7684\u6587\u4EF6\uFF08\u79D2\uFF09",
    quietSecondsDesc: "\u5728\u6B64\u65F6\u95F4\u5185\u4FEE\u6539\u8FC7\u7684\u6587\u4EF6\u4F1A\u88AB\u81EA\u52A8\u626B\u63CF\u8DF3\u8FC7\u3002\u9ED8\u8BA4\uFF1A600\uFF0810 \u5206\u949F\uFF09",
    autoScanMinSize: "\u81EA\u52A8\u626B\u63CF\u5FFD\u7565\u5C0F\u4E8E\u6B64\u5927\u5C0F\u7684\u6587\u4EF6\uFF08MiB\uFF09",
    autoScanMinSizeDesc: "\u4EC5\u5BF9\u81EA\u52A8\u626B\u63CF\u751F\u6548\uFF0C\u624B\u52A8\u626B\u63CF\u4E0D\u53D7\u5F71\u54CD\u3002\u8BBE\u4E3A 0 \u8868\u793A\u4E0A\u4F20\u6240\u6709\u6587\u4EF6\u3002",
    // Settings - File Types
    fileTypes: "\u7B2C\u4E09\u6B65\uFF1A\u9009\u62E9\u8981\u4E0A\u4F20\u7684\u6587\u4EF6\u7C7B\u578B",
    fileTypesDesc: "\u70B9\u51FB\u6587\u4EF6\u7C7B\u578B\u6765\u5207\u6362\u3002\u9009\u4E2D\u7684\u7C7B\u578B\u5728\u626B\u63CF\u65F6\u4F1A\u88AB\u4E0A\u4F20\u3002",
    extCount: "{enabled}/{total} \u5DF2\u542F\u7528",
    categoryImage: "\u56FE\u7247",
    categoryVideo: "\u89C6\u9891",
    categoryAudio: "\u97F3\u9891",
    categoryDocument: "\u6587\u6863",
    deselectAll: "\u53D6\u6D88\u5168\u9009",
    customExtensions: "\u81EA\u5B9A\u4E49\u6587\u4EF6\u7C7B\u578B",
    customExtPlaceholder: "\u4F8B\u5982 sketch\u3001fig\u3001psd",
    addExtension: "\u6DFB\u52A0",
    removeExtension: "\u79FB\u9664",
    minSizeSection: "\u6700\u5C0F\u6587\u4EF6\u5927\u5C0F\u8FC7\u6EE4\uFF08\u9AD8\u7EA7\uFF09",
    minSizeSectionDesc: "\u53EA\u4E0A\u4F20\u5927\u4E8E\u6307\u5B9A\u5927\u5C0F\u7684\u6587\u4EF6\u3002\u8BBE\u4E3A 0 \u8868\u793A\u4E0A\u4F20\u6240\u6709\u6587\u4EF6\u3002",
    minSizeMiB: "\u6700\u5C0F\u5927\u5C0F (MiB)",
    autoCandidate: "\u5B9A\u65F6\u626B\u63CF\u5305\u542B",
    autoScanShort: "\u5B9A\u65F6",
    advancedSettings: "\u9AD8\u7EA7\u8BBE\u7F6E",
    replacementType: "\u66FF\u6362\u683C\u5F0F",
    markdownLink: "Markdown \u94FE\u63A5",
    imageEmbed: "\u56FE\u7247\u5D4C\u5165",
    audioTag: "\u97F3\u9891\u6807\u7B7E",
    videoTag: "\u89C6\u9891\u6807\u7B7E",
    // Settings - Log
    recentLog: "\u6700\u8FD1\u6D3B\u52A8",
    pendingDeletes: "\u5F85\u5EF6\u8FDF\u5220\u9664",
    noLogs: "\u6682\u65E0\u6D3B\u52A8\u8BB0\u5F55\u3002\u626B\u63CF\u4E00\u7BC7\u6587\u6863\u5373\u53EF\u5F00\u59CB\u3002"
  }
};
function detectLocaleFromApp(getLanguage2) {
  const lang = getLanguage2();
  return String(lang).toLowerCase().startsWith("zh") ? "zh" : "en";
}
function t(locale, key, params = {}) {
  const pack = I18N[locale] || I18N.en;
  const template = pack[key] || I18N.en[key] || key;
  return template.replace(/\{(\w+)\}/g, (_, name) => String(params[name] ?? ""));
}

// src/candidate-modal.ts
var import_obsidian2 = require("obsidian");
var CATEGORY_ICONS = {
  image: "\u{1F4F7}",
  video: "\u{1F3AC}",
  audio: "\u{1F3B5}",
  document: "\u{1F4C4}"
};
function makeT(plugin) {
  return (key, params) => plugin.t(key, params);
}
var CandidateModal = class extends import_obsidian2.Modal {
  plugin;
  noteFile;
  candidates;
  selected;
  viewMode = "list";
  activeFilter = "all";
  progressBar = null;
  progressText = null;
  constructor(app, plugin, noteFile, candidates) {
    super(app);
    this.plugin = plugin;
    this.noteFile = noteFile;
    this.candidates = candidates;
    this.selected = new Set(candidates.map((c) => c.file.path));
  }
  onOpen() {
    this.modalEl.addClass("attachment-imagebed-manager-modal");
    this.renderContent();
  }
  getFilteredCandidates() {
    if (this.activeFilter === "all")
      return this.candidates;
    return this.candidates.filter((c) => {
      const cat = getCategoryForExt(c.ext);
      return cat?.id === this.activeFilter;
    });
  }
  getCategoryCounts() {
    const counts = /* @__PURE__ */ new Map();
    counts.set("all", this.candidates.length);
    for (const c of this.candidates) {
      const cat = getCategoryForExt(c.ext);
      const id = cat?.id || "other";
      counts.set(id, (counts.get(id) || 0) + 1);
    }
    return counts;
  }
  renderContent() {
    const { contentEl } = this;
    contentEl.empty();
    const t2 = makeT(this.plugin);
    new import_obsidian2.Setting(contentEl).setName(t2("replaceTitle")).setHeading();
    contentEl.createEl("p", {
      text: t2("candidateSummary", { path: this.noteFile.path, count: this.candidates.length }),
      cls: "attachment-imagebed-manager-summary"
    });
    const layout = contentEl.createDiv({ cls: "attachment-imagebed-manager-modal-layout" });
    this.renderSidebar(layout);
    const rightPanel = layout.createDiv({ cls: "attachment-imagebed-manager-modal-main" });
    this.renderViewToggle(rightPanel);
    const filtered = this.getFilteredCandidates();
    if (this.viewMode === "list") {
      this.renderListView(rightPanel, filtered);
    } else {
      this.renderGalleryView(rightPanel, filtered);
    }
    const bottomBar = rightPanel.createDiv({ cls: "attachment-imagebed-manager-bottom-bar" });
    const selectAllLabel = bottomBar.createEl("label", { cls: "attachment-imagebed-manager-select-all" });
    const selectAllCb = selectAllLabel.createEl("input", { type: "checkbox" });
    const filteredPaths = new Set(filtered.map((c) => c.file.path));
    selectAllCb.checked = filteredPaths.size > 0 && [...filteredPaths].every((p) => this.selected.has(p));
    selectAllCb.addEventListener("change", () => {
      if (selectAllCb.checked) {
        for (const p of filteredPaths)
          this.selected.add(p);
      } else {
        for (const p of filteredPaths)
          this.selected.delete(p);
      }
      this.renderContent();
    });
    selectAllLabel.createSpan({ text: t2("selectAll") });
    const actions = bottomBar.createDiv({ cls: "attachment-imagebed-manager-actions" });
    new import_obsidian2.Setting(actions).addButton(
      (button) => button.setButtonText(t2("cancel")).onClick(() => this.close())
    ).addButton(
      (button) => button.setButtonText(t2("uploadReplace")).setCta().onClick(() => this.replaceSelected())
    );
  }
  renderSidebar(containerEl) {
    const t2 = makeT(this.plugin);
    const counts = this.getCategoryCounts();
    const sidebar = containerEl.createDiv({ cls: "attachment-imagebed-manager-sidebar" });
    const allItem = sidebar.createDiv({
      cls: `attachment-imagebed-manager-sidebar-item${this.activeFilter === "all" ? " attachment-imagebed-manager-sidebar-active" : ""}`
    });
    allItem.createSpan({ text: t2("filterAll") });
    allItem.createSpan({ text: String(counts.get("all") || 0), cls: "attachment-imagebed-manager-sidebar-count" });
    allItem.addEventListener("click", () => {
      this.activeFilter = "all";
      this.renderContent();
    });
    for (const cat of FILE_CATEGORIES) {
      const count = counts.get(cat.id);
      if (!count)
        continue;
      const item = sidebar.createDiv({
        cls: `attachment-imagebed-manager-sidebar-item${this.activeFilter === cat.id ? " attachment-imagebed-manager-sidebar-active" : ""}`
      });
      const icon = CATEGORY_ICONS[cat.id] || "";
      item.createSpan({ text: `${icon} ${t2(cat.nameKey)}` });
      item.createSpan({ text: String(count), cls: "attachment-imagebed-manager-sidebar-count" });
      item.addEventListener("click", () => {
        this.activeFilter = cat.id;
        this.renderContent();
      });
    }
    const otherCount = counts.get("other");
    if (otherCount) {
      const item = sidebar.createDiv({
        cls: `attachment-imagebed-manager-sidebar-item${this.activeFilter === "other" ? " attachment-imagebed-manager-sidebar-active" : ""}`
      });
      item.createSpan({ text: t2("filterOther") });
      item.createSpan({ text: String(otherCount), cls: "attachment-imagebed-manager-sidebar-count" });
      item.addEventListener("click", () => {
        this.activeFilter = "other";
        this.renderContent();
      });
    }
  }
  renderViewToggle(containerEl) {
    const t2 = makeT(this.plugin);
    const toggleEl = containerEl.createDiv({ cls: "attachment-imagebed-manager-view-toggle" });
    const listBtn = toggleEl.createEl("button", {
      text: t2("viewList"),
      cls: this.viewMode === "list" ? "attachment-imagebed-manager-view-btn-active" : ""
    });
    const galleryBtn = toggleEl.createEl("button", {
      text: t2("viewGallery"),
      cls: this.viewMode === "gallery" ? "attachment-imagebed-manager-view-btn-active" : ""
    });
    listBtn.addEventListener("click", () => {
      if (this.viewMode !== "list") {
        this.viewMode = "list";
        this.renderContent();
      }
    });
    galleryBtn.addEventListener("click", () => {
      if (this.viewMode !== "gallery") {
        this.viewMode = "gallery";
        this.renderContent();
      }
    });
  }
  renderListView(containerEl, filtered) {
    const t2 = makeT(this.plugin);
    const list = containerEl.createDiv({ cls: "attachment-imagebed-manager-list" });
    for (const candidate of filtered) {
      const row = list.createDiv({ cls: "attachment-imagebed-manager-row" });
      const checkbox = row.createEl("input", { type: "checkbox" });
      checkbox.checked = this.selected.has(candidate.file.path);
      checkbox.addEventListener("change", () => {
        if (checkbox.checked)
          this.selected.add(candidate.file.path);
        else
          this.selected.delete(candidate.file.path);
      });
      row.appendChild(this.createPreview(candidate));
      const body = row.createDiv();
      body.createDiv({ text: candidate.file.name, cls: "attachment-imagebed-manager-title" });
      body.createDiv({
        text: `${candidate.file.path} \xB7 ${formatBytes(candidate.sizeBytes)} \xB7 ${t2("referenceCount", { count: candidate.referenceCount })}`,
        cls: "attachment-imagebed-manager-meta"
      });
      row.createDiv({
        text: candidate.replacement,
        cls: "attachment-imagebed-manager-meta"
      });
    }
  }
  renderGalleryView(containerEl, filtered) {
    const gallery = containerEl.createDiv({ cls: "attachment-imagebed-manager-gallery" });
    for (const candidate of filtered) {
      const card = gallery.createDiv({ cls: "attachment-imagebed-manager-gallery-card" });
      const previewArea = card.createDiv({ cls: "attachment-imagebed-manager-gallery-preview" });
      if (isPreviewableImage(candidate.file.extension)) {
        const image = previewArea.createEl("img");
        image.src = this.app.vault.getResourcePath(candidate.file);
        image.alt = candidate.file.name;
        image.loading = "lazy";
      } else {
        const badge = previewArea.createDiv({ cls: "attachment-imagebed-manager-gallery-badge" });
        badge.textContent = candidate.file.extension.toUpperCase();
      }
      const info = card.createDiv({ cls: "attachment-imagebed-manager-gallery-info" });
      const checkbox = info.createEl("input", { type: "checkbox" });
      checkbox.checked = this.selected.has(candidate.file.path);
      checkbox.addEventListener("change", () => {
        if (checkbox.checked)
          this.selected.add(candidate.file.path);
        else
          this.selected.delete(candidate.file.path);
      });
      info.createDiv({ text: candidate.file.name, cls: "attachment-imagebed-manager-gallery-name" });
      info.createDiv({
        text: formatBytes(candidate.sizeBytes),
        cls: "attachment-imagebed-manager-gallery-size"
      });
    }
  }
  createPreview(candidate) {
    const preview = (0, import_obsidian2.createDiv)({ cls: "attachment-imagebed-manager-preview" });
    if (isPreviewableImage(candidate.file.extension)) {
      const image = preview.createEl("img");
      image.src = this.app.vault.getResourcePath(candidate.file);
      image.alt = candidate.file.name;
      image.loading = "lazy";
      return preview;
    }
    preview.createDiv({
      cls: "attachment-imagebed-manager-file-badge",
      text: candidate.file.extension.toUpperCase()
    });
    return preview;
  }
  async replaceSelected() {
    const t2 = makeT(this.plugin);
    const chosen = this.candidates.filter((c) => this.selected.has(c.file.path));
    if (!chosen.length) {
      new import_obsidian2.Notice(t2("noSelected"));
      return;
    }
    this.renderProgress(chosen.length);
    try {
      const result = await this.plugin.replaceCandidates(this.noteFile, chosen, (state) => {
        this.updateProgress(state);
      });
      new import_obsidian2.Notice(t2("replacedNotice", { count: result.replaced }));
      this.renderDeleteConfirmation(result.localFiles || []);
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      console.error("Attachment replacement failed", error);
      new import_obsidian2.Notice(t2("replaceFailed", { error: message }), 1e4);
      this.renderError(error instanceof Error ? error : new Error(message));
    }
  }
  renderProgress(total) {
    const t2 = makeT(this.plugin);
    const { contentEl } = this;
    contentEl.empty();
    new import_obsidian2.Setting(contentEl).setName(t2("uploadingTitle")).setHeading();
    contentEl.createEl("p", {
      text: t2("preparing", { count: total }),
      cls: "attachment-imagebed-manager-summary"
    });
    this.progressBar = contentEl.createEl("progress", {
      cls: "attachment-imagebed-manager-progress"
    });
    this.progressBar.max = 100;
    this.progressBar.value = 0;
    this.progressText = contentEl.createDiv({
      text: t2("starting"),
      cls: "attachment-imagebed-manager-meta"
    });
  }
  updateProgress(state) {
    if (!this.progressBar || !this.progressText)
      return;
    const t2 = makeT(this.plugin);
    const total = Math.max(1, state.total || 1);
    const value = Math.min(100, Math.round((state.current || 0) / total * 100));
    this.progressBar.value = value;
    const phaseMap = {
      uploading: t2("phaseUploading"),
      uploaded: t2("phaseUploaded"),
      rewriting: t2("phaseRewriting"),
      trashing: t2("phaseTrashing"),
      scheduling: t2("phaseScheduling"),
      done: t2("phaseDone")
    };
    const phaseText = phaseMap[state.phase] || state.phase;
    this.progressText.setText(`${phaseText}: ${state.label || ""} (${state.current || 0}/${total})`);
  }
  renderDeleteConfirmation(localFiles) {
    const t2 = makeT(this.plugin);
    const { contentEl } = this;
    contentEl.empty();
    new import_obsidian2.Setting(contentEl).setName(t2("linksReplacedTitle")).setHeading();
    contentEl.createEl("p", {
      text: t2("linksReplacedDesc"),
      cls: "attachment-imagebed-manager-summary"
    });
    if (localFiles.length) {
      const list = contentEl.createDiv({ cls: "attachment-imagebed-manager-delete-list" });
      for (const fileRecord of localFiles) {
        list.createDiv({
          text: `${fileRecord.name} \xB7 ${fileRecord.path}`,
          cls: "attachment-imagebed-manager-meta"
        });
      }
    }
    const actions = contentEl.createDiv({ cls: "attachment-imagebed-manager-actions" });
    new import_obsidian2.Setting(actions).addButton(
      (button) => button.setButtonText(t2("keepLocal")).onClick(() => this.close())
    ).addButton(
      (button) => button.setButtonText(t2("deleteLocal")).setDestructive().onClick(async () => {
        try {
          await this.plugin.deleteLocalFileRecords(this.noteFile, localFiles, "manual-delete");
          new import_obsidian2.Notice(t2("movedToTrash", { count: localFiles.length }));
          this.close();
        } catch (error) {
          const message = error instanceof Error ? error.message : String(error);
          console.error("Attachment local delete failed", error);
          new import_obsidian2.Notice(t2("localDeleteFailed", { error: message }), 1e4);
          this.renderError(error instanceof Error ? error : new Error(message));
        }
      })
    );
  }
  renderError(error) {
    const t2 = makeT(this.plugin);
    const { contentEl } = this;
    contentEl.createEl("p", {
      text: error.message || String(error),
      cls: "attachment-imagebed-manager-summary"
    });
    const actions = contentEl.createDiv({ cls: "attachment-imagebed-manager-actions" });
    new import_obsidian2.Setting(actions).addButton(
      (button) => button.setButtonText(t2("close")).onClick(() => this.close())
    );
  }
};

// src/dry-run-modal.ts
var import_obsidian3 = require("obsidian");
function makeT2(plugin) {
  return (key, params) => plugin.t(key, params);
}
var DryRunModal = class extends import_obsidian3.Modal {
  plugin;
  count;
  samples;
  constructor(app, plugin, count, samples) {
    super(app);
    this.plugin = plugin;
    this.count = count;
    this.samples = samples;
  }
  onOpen() {
    const t2 = makeT2(this.plugin);
    const { contentEl } = this;
    contentEl.empty();
    new import_obsidian3.Setting(contentEl).setName(t2("vaultScanTitle")).setHeading();
    contentEl.createEl("p", { text: t2("vaultScanFound", { count: this.count }) });
    if (this.samples.length) {
      contentEl.createEl("pre", {
        text: this.samples.join("\n"),
        cls: "attachment-imagebed-manager-log"
      });
    }
  }
};

// src/settings-tab.ts
var import_obsidian4 = require("obsidian");
function makeT3(plugin) {
  return (key, params) => plugin.t(key, params);
}
var CATEGORY_ICONS2 = {
  image: "\u{1F4F7}",
  video: "\u{1F3AC}",
  audio: "\u{1F3B5}",
  document: "\u{1F4C4}"
};
var AttachmentImagebedSettingTab = class extends import_obsidian4.PluginSettingTab {
  plugin;
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    const t2 = makeT3(this.plugin);
    new import_obsidian4.Setting(containerEl).setName(t2("settingsTitle")).setHeading();
    this.renderSetupStatus(containerEl);
    this.renderS3Settings(containerEl);
    this.renderGeneralSettings(containerEl);
    if (!this.plugin.isMobile && this.plugin.settings.autoScanEnabled) {
      this.renderFileTypeSettings(containerEl);
    }
    this.renderLogSection(containerEl);
  }
  isS3Configured() {
    const s3 = this.plugin.settings.s3;
    return !!(s3.endpoint.trim() && s3.bucketName.trim() && s3.accessKeyId.trim() && s3.secretAccessKey.trim() && s3.customDomainName.trim());
  }
  renderSetupStatus(containerEl) {
    const t2 = makeT3(this.plugin);
    const configured = this.isS3Configured();
    const statusEl = containerEl.createDiv({ cls: "attachment-imagebed-manager-status" });
    const icon = statusEl.createEl("span", {
      cls: configured ? "attachment-imagebed-manager-status-ok" : "attachment-imagebed-manager-status-warn"
    });
    icon.textContent = configured ? "\u2705" : "\u26A0\uFE0F";
    statusEl.createSpan({
      text: configured ? t2("setupComplete") : t2("setupIncomplete")
    });
  }
  renderS3Settings(containerEl) {
    const t2 = makeT3(this.plugin);
    const save = () => this.plugin.saveSettings();
    const debouncedSave = debounce(save, 500);
    new import_obsidian4.Setting(containerEl).setName(t2("s3Storage")).setHeading();
    containerEl.createEl("p", {
      text: t2("s3SetupGuide"),
      cls: "attachment-imagebed-manager-guide"
    });
    new import_obsidian4.Setting(containerEl).setName(t2("provider")).setDesc(t2("providerDesc")).addDropdown(
      (dropdown) => dropdown.addOption("r2", t2("providerR2")).addOption("s3", t2("providerS3")).addOption("minio", t2("providerMinio")).addOption("custom", t2("providerCustom")).setValue(this.plugin.settings.s3.provider).onChange((value) => {
        const provider = value;
        this.plugin.settings.s3.provider = provider;
        if (provider === "r2") {
          this.plugin.settings.s3.region = "auto";
        } else if (!this.plugin.settings.s3.region || this.plugin.settings.s3.region === "auto") {
          this.plugin.settings.s3.region = "us-east-1";
        }
        void save();
        this.display();
      })
    );
    if (this.plugin.settings.s3.provider !== "r2") {
      new import_obsidian4.Setting(containerEl).setName(t2("region")).setDesc(t2("regionDesc")).addText(
        (text) => text.setValue(this.plugin.settings.s3.region).onChange((value) => {
          this.plugin.settings.s3.region = value.trim() || "us-east-1";
          void debouncedSave();
        })
      );
    }
    const s3Fields = [
      ["endpoint", t2("endpoint"), t2("endpointDesc"), false],
      ["bucketName", t2("bucketName"), t2("bucketNameDesc"), false],
      ["accessKeyId", t2("accessKeyId"), t2("accessKeyIdDesc"), false],
      ["secretAccessKey", t2("secretAccessKey"), "", true],
      ["customDomainName", t2("publicDomain"), t2("publicDomainDesc"), false]
    ];
    for (const [key, label, desc, isPassword] of s3Fields) {
      new import_obsidian4.Setting(containerEl).setName(label).setDesc(desc).addText((text) => {
        if (isPassword)
          text.inputEl.type = "password";
        text.setPlaceholder(isPassword ? "********" : "");
        const s3Key = key;
        text.setValue(String(this.plugin.settings.s3[s3Key] || "")).onChange((value) => {
          const trimmed = value.trim();
          switch (s3Key) {
            case "endpoint":
              this.plugin.settings.s3.endpoint = trimmed;
              break;
            case "bucketName":
              this.plugin.settings.s3.bucketName = trimmed;
              break;
            case "accessKeyId":
              this.plugin.settings.s3.accessKeyId = trimmed;
              break;
            case "secretAccessKey":
              this.plugin.settings.s3.secretAccessKey = trimmed;
              break;
            case "customDomainName":
              this.plugin.settings.s3.customDomainName = trimmed;
              break;
            case "pathTemplate":
              this.plugin.settings.s3.pathTemplate = trimmed;
              break;
            case "provider":
              this.plugin.settings.s3.provider = trimmed;
              break;
            case "region":
              this.plugin.settings.s3.region = trimmed;
              break;
          }
          void debouncedSave();
        });
      });
    }
    new import_obsidian4.Setting(containerEl).setName(t2("objectPathTemplate")).setDesc(t2("pathTemplateDesc")).addText(
      (text) => text.setPlaceholder("attachments/{ext}/{hash2}/{hash}.{ext}").setValue(String(this.plugin.settings.s3.pathTemplate || "")).onChange((value) => {
        this.plugin.settings.s3.pathTemplate = value.trim();
        void debouncedSave();
      })
    );
    new import_obsidian4.Setting(containerEl).setName(t2("testConnection")).setDesc(t2("testConnectionDesc")).addButton(
      (button) => button.setButtonText(t2("testConnection")).setCta().onClick(async () => {
        try {
          this.plugin.ensureS3Settings();
        } catch (error) {
          new import_obsidian4.Notice(error instanceof Error ? error.message : String(error));
          return;
        }
        button.setButtonText(t2("testing"));
        button.setDisabled(true);
        try {
          await testS3Connection(this.plugin.settings.s3);
          new import_obsidian4.Notice(t2("testConnectionSuccess"));
        } catch (error) {
          const errMsg = error instanceof Error ? error.message : String(error);
          new import_obsidian4.Notice(t2("testConnectionFailed", { error: errMsg }), 1e4);
        } finally {
          button.setButtonText(t2("testConnection"));
          button.setDisabled(false);
        }
      })
    );
  }
  renderGeneralSettings(containerEl) {
    const t2 = makeT3(this.plugin);
    const save = () => this.plugin.saveSettings();
    const debouncedSave = debounce(save, 500);
    new import_obsidian4.Setting(containerEl).setName(t2("generalSettings")).setHeading();
    new import_obsidian4.Setting(containerEl).setName(t2("pluginEnabled")).setDesc(t2("pluginEnabledDesc")).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.enabled).onChange((value) => {
        this.plugin.settings.enabled = value;
        this.plugin.configureAutoScan();
        void save();
      })
    );
    new import_obsidian4.Setting(containerEl).setName(t2("attachmentRoot")).setDesc(t2("attachmentRootDesc")).addText(
      (text) => text.setValue(this.plugin.settings.attachmentRoot).onChange((value) => {
        this.plugin.settings.attachmentRoot = value.trim() || "99 Attachments";
        void save();
      })
    );
    new import_obsidian4.Setting(containerEl).setName(t2("deletePolicy")).setDesc(t2("deletePolicyDesc")).addDropdown((dropdown) => {
      dropdown.addOption("confirm", t2("deleteConfirm")).addOption("immediate", t2("deleteImmediate"));
      if (!this.plugin.isMobile) {
        dropdown.addOption("delayed", t2("deleteDelayed"));
      }
      dropdown.setValue(this.plugin.settings.deletePolicy).onChange((value) => {
        this.plugin.settings.deletePolicy = value;
        void save();
        this.display();
      });
    });
    if (!this.plugin.isMobile && this.plugin.settings.deletePolicy === "delayed") {
      new import_obsidian4.Setting(containerEl).setName(t2("deleteDelayHours")).setDesc(t2("deleteDelayHoursDesc")).addText(
        (text) => text.setValue(String(this.plugin.settings.autoDeleteDelayHours)).onChange((value) => {
          this.plugin.settings.autoDeleteDelayHours = Math.max(0, Number(value) || 24);
          void debouncedSave();
        })
      );
    }
    if (!this.plugin.isMobile) {
      new import_obsidian4.Setting(containerEl).setName(t2("automaticScan")).setDesc(t2("automaticScanDesc")).addToggle(
        (toggle) => toggle.setValue(this.plugin.settings.autoScanEnabled).onChange((value) => {
          this.plugin.settings.autoScanEnabled = value;
          this.plugin.configureAutoScan();
          void save();
          this.display();
        })
      );
      if (this.plugin.settings.autoScanEnabled) {
        new import_obsidian4.Setting(containerEl).setName(t2("scanInterval")).setDesc(t2("scanIntervalDesc")).addText(
          (text) => text.setValue(String(this.plugin.settings.scanIntervalMinutes)).onChange((value) => {
            this.plugin.settings.scanIntervalMinutes = Number(value) || 30;
            this.plugin.configureAutoScan();
            void debouncedSave();
          })
        );
        new import_obsidian4.Setting(containerEl).setName(t2("quietSeconds")).setDesc(t2("quietSecondsDesc")).addText(
          (text) => text.setValue(String(this.plugin.settings.quietSeconds)).onChange((value) => {
            this.plugin.settings.quietSeconds = Number(value) || 0;
            void debouncedSave();
          })
        );
        new import_obsidian4.Setting(containerEl).setName(t2("autoScanMinSize")).setDesc(t2("autoScanMinSizeDesc")).addText(
          (text) => text.setValue(String(this.plugin.settings.autoScanMinSizeMiB || 0)).onChange((value) => {
            this.plugin.settings.autoScanMinSizeMiB = Math.max(0, Number(value) || 0);
            void debouncedSave();
          })
        );
      }
    } else {
      const hintEl = containerEl.createEl("p", {
        cls: "setting-item-description"
      });
      hintEl.textContent = t2("mobileHint");
    }
  }
  renderFileTypeSettings(containerEl) {
    const t2 = makeT3(this.plugin);
    new import_obsidian4.Setting(containerEl).setName(t2("fileTypes")).setHeading();
    containerEl.createEl("p", {
      text: t2("fileTypesDesc"),
      cls: "attachment-imagebed-manager-guide"
    });
    for (const category of FILE_CATEGORIES) {
      this.renderCategory(containerEl, category);
    }
    this.renderCustomExtensions(containerEl);
  }
  renderCategory(containerEl, category) {
    const t2 = makeT3(this.plugin);
    const settings = this.plugin.settings;
    const enabledSet = new Set(settings.enabledExtensions);
    const autoSet = new Set(settings.autoCandidateExts);
    const icon = CATEGORY_ICONS2[category.id] || "";
    const enabledCount = category.extensions.filter((e) => enabledSet.has(e)).length;
    const totalCount = category.extensions.length;
    const catEnabled = enabledCount === totalCount;
    const catPartiallyEnabled = !catEnabled && enabledCount > 0;
    const defaultExpanded = enabledCount > 0;
    const card = containerEl.createDiv({ cls: "attachment-imagebed-manager-category" });
    const headerRow = card.createDiv({ cls: "attachment-imagebed-manager-category-header" });
    const catCheckbox = headerRow.createEl("input", { type: "checkbox" });
    catCheckbox.checked = catEnabled;
    catCheckbox.indeterminate = catPartiallyEnabled;
    const catLabel = headerRow.createEl("span", { cls: "attachment-imagebed-manager-category-name" });
    catLabel.textContent = `${icon} ${t2(category.nameKey)}`;
    const countLabel = headerRow.createEl("span", { cls: "attachment-imagebed-manager-category-count" });
    countLabel.textContent = t2("extCount", { enabled: enabledCount, total: totalCount });
    const autoEnabled = category.extensions.filter((e) => enabledSet.has(e)).every((e) => autoSet.has(e));
    const autoLabel = headerRow.createEl("label", { cls: "attachment-imagebed-manager-auto-label" });
    const autoCheckbox = autoLabel.createEl("input", { type: "checkbox" });
    autoCheckbox.checked = autoEnabled;
    autoLabel.createSpan({ text: t2("autoScanShort") });
    const toggleBtn = headerRow.createEl("span", { cls: "attachment-imagebed-manager-category-toggle" });
    toggleBtn.textContent = defaultExpanded ? "\u25BC" : "\u25B6";
    const chipsBody = card.createDiv({ cls: "attachment-imagebed-manager-category-body" });
    if (!defaultExpanded)
      chipsBody.addClass("attachment-imagebed-manager-collapsed");
    const chips = chipsBody.createDiv({ cls: "attachment-imagebed-manager-chips" });
    for (const ext of category.extensions) {
      const chip = chips.createEl("span", { cls: "attachment-imagebed-manager-chip" });
      if (enabledSet.has(ext))
        chip.addClass("attachment-imagebed-manager-chip-active");
      chip.textContent = `.${ext}`;
      chip.addEventListener("click", () => {
        if (enabledSet.has(ext))
          enabledSet.delete(ext);
        else
          enabledSet.add(ext);
        settings.enabledExtensions = Array.from(enabledSet);
        void this.plugin.saveSettings();
        this.display();
      });
    }
    catCheckbox.addEventListener("change", () => {
      for (const ext of category.extensions) {
        if (catCheckbox.checked)
          enabledSet.add(ext);
        else
          enabledSet.delete(ext);
      }
      settings.enabledExtensions = Array.from(enabledSet);
      void this.plugin.saveSettings();
      this.display();
    });
    autoCheckbox.addEventListener("change", () => {
      const enabledInCat = category.extensions.filter((e) => enabledSet.has(e));
      for (const ext of enabledInCat) {
        if (autoCheckbox.checked)
          autoSet.add(ext);
        else
          autoSet.delete(ext);
      }
      settings.autoCandidateExts = Array.from(autoSet);
      void this.plugin.saveSettings();
      this.display();
    });
    let expanded = defaultExpanded;
    toggleBtn.addEventListener("click", () => {
      expanded = !expanded;
      chipsBody.toggleClass("attachment-imagebed-manager-collapsed", !expanded);
      toggleBtn.textContent = expanded ? "\u25BC" : "\u25B6";
    });
  }
  renderCustomExtensions(containerEl) {
    const t2 = makeT3(this.plugin);
    const settings = this.plugin.settings;
    const enabledSet = new Set(settings.enabledExtensions);
    const autoSet = new Set(settings.autoCandidateExts);
    const allKnownExts = FILE_CATEGORIES.flatMap((c) => c.extensions);
    const customExts = settings.customExtensions.filter((e) => !allKnownExts.includes(e));
    const card = containerEl.createDiv({ cls: "attachment-imagebed-manager-category" });
    const headerRow = card.createDiv({ cls: "attachment-imagebed-manager-category-header" });
    headerRow.createEl("span", { cls: "attachment-imagebed-manager-category-name" }).textContent = `\u2795 ${t2("customExtensions")}`;
    let inputValue = "";
    const inputRow = card.createDiv({ cls: "attachment-imagebed-manager-custom-input-row" });
    const input = inputRow.createEl("input", {
      type: "text",
      placeholder: t2("customExtPlaceholder")
    });
    input.addEventListener("input", () => {
      inputValue = input.value;
    });
    const addBtn = inputRow.createEl("button", { text: t2("addExtension") });
    addBtn.addEventListener("click", () => {
      const exts = inputValue.split(/[,\s]+/).map((e) => e.trim().replace(/^\./, "").toLowerCase()).filter(Boolean);
      for (const ext of exts) {
        if (!settings.customExtensions.includes(ext))
          settings.customExtensions.push(ext);
        if (!enabledSet.has(ext))
          enabledSet.add(ext);
      }
      settings.enabledExtensions = Array.from(enabledSet);
      void this.plugin.saveSettings();
      this.display();
    });
    if (customExts.length > 0) {
      const tagContainer = card.createDiv({ cls: "attachment-imagebed-manager-custom-tags" });
      for (const ext of customExts) {
        const tag = tagContainer.createEl("span", { cls: "attachment-imagebed-manager-custom-tag" });
        const extCheckbox = tag.createEl("input", { type: "checkbox" });
        extCheckbox.checked = enabledSet.has(ext);
        extCheckbox.addEventListener("change", () => {
          if (extCheckbox.checked)
            enabledSet.add(ext);
          else
            enabledSet.delete(ext);
          settings.enabledExtensions = Array.from(enabledSet);
          void this.plugin.saveSettings();
          this.display();
        });
        tag.createSpan({ text: `.${ext}` });
        const autoCb = tag.createEl("input", { type: "checkbox" });
        autoCb.checked = autoSet.has(ext);
        autoCb.title = t2("autoScanShort");
        autoCb.addEventListener("change", () => {
          if (autoCb.checked)
            autoSet.add(ext);
          else
            autoSet.delete(ext);
          settings.autoCandidateExts = Array.from(autoSet);
          void this.plugin.saveSettings();
        });
        const autoSpan = tag.createEl("span", { cls: "attachment-imagebed-manager-auto-text" });
        autoSpan.textContent = t2("autoScanShort");
        const removeBtn = tag.createEl("span", { cls: "attachment-imagebed-manager-remove" });
        removeBtn.textContent = "\xD7";
        removeBtn.addEventListener("click", () => {
          settings.customExtensions = settings.customExtensions.filter((e) => e !== ext);
          enabledSet.delete(ext);
          settings.enabledExtensions = Array.from(enabledSet);
          delete settings.minSizeRules[ext];
          delete settings.customReplacements[ext];
          autoSet.delete(ext);
          settings.autoCandidateExts = Array.from(autoSet);
          void this.plugin.saveSettings();
          this.display();
        });
      }
    }
  }
  renderLogSection(containerEl) {
    const t2 = makeT3(this.plugin);
    const settings = this.plugin.settings;
    new import_obsidian4.Setting(containerEl).setName(t2("recentLog")).setHeading();
    if ((settings.pendingDeletes || []).length) {
      new import_obsidian4.Setting(containerEl).setName(t2("pendingDeletes")).setHeading();
      containerEl.createEl("pre", {
        text: settings.pendingDeletes.slice(0, 20).map((entry) => `${new Date(entry.dueAt).toLocaleString()} ${entry.sourcePath}`).join("\n"),
        cls: "attachment-imagebed-manager-log"
      });
    }
    const logs = (settings.logs || []).slice(0, 20);
    if (logs.length > 0) {
      containerEl.createEl("pre", {
        text: logs.map((log) => `${log.time} ${log.status} ${log.sourcePath || ""} -> ${log.remoteUrl || ""}`).join("\n"),
        cls: "attachment-imagebed-manager-log"
      });
    } else {
      containerEl.createEl("p", {
        text: t2("noLogs"),
        cls: "attachment-imagebed-manager-meta"
      });
    }
  }
};

// src/plugin.ts
var AttachmentImagebedManagerPlugin = class extends import_obsidian5.Plugin {
  locale;
  autoScanTimer = null;
  isMobile = false;
  async onload() {
    await this.loadSettings();
    this.locale = detectLocaleFromApp(import_obsidian5.getLanguage);
    this.isMobile = import_obsidian5.Platform.isMobile;
    this.addRibbonIcon("upload-cloud", this.t("ribbonScan"), () => {
      void this.scanCurrentNote();
    });
    this.addCommand({
      id: "scan-current-note",
      name: this.t("commandScanCurrent"),
      callback: () => this.scanCurrentNote()
    });
    this.addCommand({
      id: "scan-vault-candidates-dry-run",
      name: this.t("commandScanVault"),
      callback: () => this.scanVaultDryRun()
    });
    this.addCommand({
      id: "process-delayed-deletes",
      name: this.t("commandProcessDeletes"),
      callback: () => this.processPendingDeletes()
    });
    this.addSettingTab(new AttachmentImagebedSettingTab(this.app, this));
    if (!this.isMobile) {
      await this.processPendingDeletes();
      this.registerInterval(
        window.setInterval(() => {
          this.processPendingDeletes().catch((error) => {
            console.error(this.t("delayedDeleteFailed"), error);
          });
        }, 60 * 1e3)
      );
    }
    this.configureAutoScan();
  }
  onunload() {
    if (this.autoScanTimer)
      window.clearInterval(this.autoScanTimer);
  }
  async loadSettings() {
    const loaded = await this.loadData();
    this.settings = mergeSettings(DEFAULT_SETTINGS, loaded || {});
  }
  async saveSettings() {
    const toSave = { ...this.settings };
    toSave.logs = this.settings.logs.slice(0, 50);
    await this.saveData(toSave);
  }
  t(key, params = {}) {
    return t(this.locale, key, params);
  }
  configureAutoScan() {
    if (this.autoScanTimer)
      window.clearInterval(this.autoScanTimer);
    this.autoScanTimer = null;
    if (this.isMobile)
      return;
    if (!this.settings.enabled || !this.settings.autoScanEnabled)
      return;
    const minutes = Math.max(1, Number(this.settings.scanIntervalMinutes) || 30);
    this.autoScanTimer = window.setInterval(() => {
      this.runAutoScan().catch((error) => {
        console.error("Auto scan failed", error);
        new import_obsidian5.Notice(this.t("autoScanFailed", { error: error instanceof Error ? error.message : String(error) }));
      });
    }, minutes * 60 * 1e3);
  }
  async scanCurrentNote() {
    if (!this.settings.enabled) {
      new import_obsidian5.Notice(this.t("disabled"));
      return;
    }
    const activeFile = this.app.workspace.getActiveFile();
    if (!activeFile || activeFile.extension !== "md") {
      new import_obsidian5.Notice(this.t("openMarkdownFirst"));
      return;
    }
    try {
      this.ensureS3Settings();
    } catch (error) {
      new import_obsidian5.Notice(error instanceof Error ? error.message : String(error));
      return;
    }
    const candidates = await this.findCandidatesInNote(activeFile, {
      requireAutoCandidate: false,
      enforceAttachmentRoot: false,
      enforceSizeRule: false,
      skipExtensionFilter: true
    });
    if (candidates.length === 0) {
      new import_obsidian5.Notice(this.t("noCandidates"));
      return;
    }
    new CandidateModal(this.app, this, activeFile, candidates).open();
  }
  async scanVaultDryRun() {
    const files = this.app.vault.getMarkdownFiles();
    let count = 0;
    const samples = [];
    const notice = new import_obsidian5.Notice(this.t("scanningVault", { current: 0, total: files.length }), 0);
    for (let i = 0; i < files.length; i++) {
      const file = files[i];
      if (i % 50 === 0) {
        notice.setMessage(this.t("scanningVault", { current: i, total: files.length }));
      }
      try {
        const candidates = await this.findCandidatesInNote(file, {
          requireAutoCandidate: true,
          enforceAttachmentRoot: true,
          enforceSizeRule: true
        });
        count += candidates.length;
        for (const candidate of candidates.slice(0, 3)) {
          if (samples.length < 20)
            samples.push(`${file.path} -> ${candidate.file.path}`);
        }
      } catch (error) {
        console.error(`Dry-run scan error for ${file.path}:`, error);
      }
    }
    notice.hide();
    new DryRunModal(this.app, this, count, samples).open();
  }
  async runAutoScan() {
    if (!this.settings.enabled || !this.settings.autoScanEnabled)
      return;
    try {
      this.ensureS3Settings();
    } catch {
    }
    const minBytes = Math.max(0, Number(this.settings.autoScanMinSizeMiB) || 0) * 1024 * 1024;
    const files = this.app.vault.getMarkdownFiles();
    let replaced = 0;
    for (const file of files) {
      try {
        if (!this.isQuiet(file))
          continue;
        const candidates = await this.findCandidatesInNote(file, {
          requireAutoCandidate: true,
          enforceAttachmentRoot: true,
          enforceSizeRule: true
        });
        const quietCandidates = candidates.filter((c) => {
          if (!this.isQuiet(c.file))
            return false;
          if (minBytes > 0 && c.sizeBytes < minBytes)
            return false;
          return true;
        });
        if (quietCandidates.length === 0)
          continue;
        const result = await this.replaceCandidates(file, quietCandidates, null, {
          deleteMode: "delayed"
        });
        replaced += result.replaced;
      } catch (error) {
        console.error(`Auto-scan error for ${file.path}:`, error);
      }
    }
    if (replaced > 0)
      new import_obsidian5.Notice(this.t("autoScanReplaced", { count: replaced }));
  }
  isQuiet(file) {
    const quietMs = Math.max(0, Number(this.settings.quietSeconds) || 0) * 1e3;
    if (!quietMs)
      return true;
    return Date.now() - file.stat.mtime >= quietMs;
  }
  async findCandidatesInNote(noteFile, options) {
    const text = await this.app.vault.read(noteFile);
    const refs = extractLocalRefs(text);
    const byKey = /* @__PURE__ */ new Map();
    for (const ref of refs) {
      const targetFile = this.resolveLinkedFile(ref.target, noteFile);
      if (!targetFile || !(targetFile instanceof import_obsidian5.TFile))
        continue;
      if (options.enforceAttachmentRoot !== false && !this.isUnderAttachmentRoot(targetFile))
        continue;
      if (this.isCoverReference(text, ref))
        continue;
      const ext = targetFile.extension.toLowerCase();
      if (ext === "md")
        continue;
      if (!options.skipExtensionFilter && !this.settings.enabledExtensions.includes(ext))
        continue;
      if (options.requireAutoCandidate && !this.settings.autoCandidateExts.includes(ext))
        continue;
      if (options.enforceSizeRule !== false && !this.meetsSizeRule(targetFile, ext))
        continue;
      const replacement = getReplacementForExt(ext, this.settings);
      const key = `${targetFile.path}::${replacement}`;
      const existing = byKey.get(key);
      if (existing) {
        existing.refs.push(ref);
        existing.referenceCount += 1;
      } else {
        byKey.set(key, {
          file: targetFile,
          ext,
          replacement,
          refs: [ref],
          referenceCount: 1,
          sizeBytes: targetFile.stat.size
        });
      }
    }
    return Array.from(byKey.values()).sort((a, b) => b.sizeBytes - a.sizeBytes);
  }
  resolveLinkedFile(target, noteFile) {
    let decoded;
    try {
      decoded = decodeURIComponent(target);
    } catch {
      decoded = target;
    }
    const direct = this.app.vault.getAbstractFileByPath(decoded);
    if (direct instanceof import_obsidian5.TFile)
      return direct;
    const fromCache = this.app.metadataCache.getFirstLinkpathDest(decoded, noteFile.path);
    if (fromCache instanceof import_obsidian5.TFile)
      return fromCache;
    const noteDir = noteFile.parent ? noteFile.parent.path : "";
    const relativePath = noteDir ? `${noteDir}/${decoded}` : decoded;
    const relative = this.app.vault.getAbstractFileByPath(relativePath);
    return relative instanceof import_obsidian5.TFile ? relative : null;
  }
  isUnderAttachmentRoot(file) {
    const root = trimSlashes(this.settings.attachmentRoot || "99 Attachments");
    return file.path === root || file.path.startsWith(`${root}/`);
  }
  isCoverReference(text, ref) {
    if (/\/cover\//i.test(ref.target))
      return true;
    const fmEnd = text.indexOf("\n---", 4);
    if (fmEnd === -1)
      return false;
    if (ref.start > fmEnd)
      return false;
    const lineStart = text.lastIndexOf("\n", ref.start) + 1;
    const lineEndIndex = text.indexOf("\n", ref.end);
    const lineEnd = lineEndIndex === -1 ? text.length : lineEndIndex;
    const line = text.slice(lineStart, lineEnd);
    return /^\s*cover\s*:/i.test(line);
  }
  meetsSizeRule(file, ext) {
    const minMiB = this.settings.minSizeRules[ext] || 0;
    const minSize = Math.max(0, minMiB) * 1024 * 1024;
    return file.stat.size >= minSize;
  }
  async replaceCandidates(noteFile, candidates, progress, options = {}) {
    const deleteMode = options.deleteMode || this.settings.deletePolicy || "confirm";
    this.ensureS3Settings();
    const originalText = await this.app.vault.read(noteFile);
    let noteChanged = false;
    let replaced = 0;
    const replacementMap = /* @__PURE__ */ new Map();
    const uploaded = /* @__PURE__ */ new Map();
    const uploadedKeys = [];
    const uniqueFiles = new Set(candidates.map((c) => c.file.path)).size;
    let completedUploads = 0;
    try {
      for (const candidate of candidates) {
        let upload = uploaded.get(candidate.file.path);
        if (!upload) {
          progress?.({
            phase: "uploading",
            current: completedUploads,
            total: uniqueFiles,
            label: candidate.file.name
          });
          upload = await this.uploadCandidate(candidate);
          uploaded.set(candidate.file.path, upload);
          uploadedKeys.push(upload.key);
          completedUploads += 1;
          progress?.({
            phase: "uploaded",
            current: completedUploads,
            total: uniqueFiles,
            label: candidate.file.name
          });
        }
        for (const ref of candidate.refs) {
          replacementMap.set(ref.raw, this.buildReplacement(ref, candidate, upload.publicUrl));
        }
      }
      progress?.({
        phase: "rewriting",
        current: completedUploads,
        total: uniqueFiles,
        label: noteFile.name
      });
      await this.app.vault.process(noteFile, (current) => {
        if (current !== originalText) {
          throw new Error(this.t("noteChanged"));
        }
        let next = current;
        for (const [raw, replacement] of replacementMap.entries()) {
          if (!next.includes(raw)) {
            throw new Error(this.t("originalLinkChanged", { link: raw }));
          }
          next = replaceAllLiteral(next, raw, replacement);
        }
        noteChanged = next !== current;
        return next;
      });
    } catch (error) {
      for (const key of uploadedKeys) {
        await deleteS3Object(this.settings.s3, key).catch(() => {
        });
      }
      throw error;
    }
    if (!noteChanged)
      return { replaced: 0 };
    const localFiles = this.buildLocalFileRecords(candidates, uploaded);
    for (const candidate of candidates)
      replaced += candidate.refs.length;
    if (deleteMode === "delayed") {
      progress?.({
        phase: "scheduling",
        current: completedUploads,
        total: uniqueFiles,
        label: this.t("phaseScheduling")
      });
      this.scheduleDelayedDeletes(noteFile, localFiles);
    } else if (deleteMode === "immediate") {
      progress?.({
        phase: "trashing",
        current: completedUploads,
        total: uniqueFiles,
        label: this.t("phaseTrashing")
      });
      await this.deleteLocalFileRecords(noteFile, localFiles, "manual-delete");
    } else {
      for (const fileRecord of localFiles) {
        this.addLog({
          status: "replaced-awaiting-delete-confirm",
          notePath: noteFile.path,
          sourcePath: fileRecord.path,
          remoteUrl: fileRecord.remoteUrl,
          trashed: false
        });
      }
    }
    await this.saveSettings();
    progress?.({
      phase: "done",
      current: uniqueFiles,
      total: uniqueFiles,
      label: this.t("phaseDone")
    });
    return { replaced, localFiles };
  }
  async uploadCandidate(candidate) {
    const binary = await this.app.vault.readBinary(candidate.file);
    const body = new Uint8Array(binary);
    const hash = await sha256Hex(body);
    const ext = candidate.file.extension.toLowerCase();
    const key = renderPathTemplate(this.settings.s3.pathTemplate, {
      ext,
      hash,
      hash2: hash.slice(0, 2),
      filename: safeFilename(candidate.file.name)
    });
    const contentType = contentTypeForExt(ext);
    await putS3Object(
      this.settings.s3,
      key,
      body,
      contentType,
      (status, text) => this.t("uploadFailed", { status, text }),
      hash
    );
    return { key, publicUrl: buildPublicUrl(this.settings.s3.customDomainName, key) };
  }
  buildReplacement(ref, candidate, publicUrl) {
    const encodedBase = encodeURI(publicUrl);
    const url = ref.fragment ? `${encodedBase}#${encodeURIComponent(ref.fragment)}` : encodedBase;
    const label = ref.label || candidate.file.basename;
    if (candidate.replacement === "image")
      return `![${escapeMarkdownLabel(label)}](${url})`;
    if (candidate.replacement === "video")
      return `<video src="${url}" controls></video>`;
    if (candidate.replacement === "audio")
      return `<audio src="${url}" controls></audio>`;
    return `[${escapeMarkdownLabel(label)}](${url})`;
  }
  buildLocalFileRecords(candidates, uploaded) {
    const byPath = /* @__PURE__ */ new Map();
    for (const candidate of candidates) {
      if (byPath.has(candidate.file.path))
        continue;
      byPath.set(candidate.file.path, {
        path: candidate.file.path,
        name: candidate.file.name,
        remoteUrl: uploaded.get(candidate.file.path)?.publicUrl || ""
      });
    }
    return Array.from(byPath.values());
  }
  scheduleDelayedDeletes(noteFile, localFiles) {
    const delayMs = Math.max(0, Number(this.settings.autoDeleteDelayHours) || 0) * 60 * 60 * 1e3;
    const dueAt = Date.now() + delayMs;
    const existing = new Set(
      (this.settings.pendingDeletes || []).map((entry) => entry.sourcePath)
    );
    for (const fileRecord of localFiles) {
      if (!existing.has(fileRecord.path)) {
        this.settings.pendingDeletes.push({
          createdAt: (/* @__PURE__ */ new Date()).toISOString(),
          dueAt,
          notePath: noteFile.path,
          sourcePath: fileRecord.path,
          remoteUrl: fileRecord.remoteUrl
        });
      }
      this.addLog({
        status: "scheduled-delayed-delete",
        notePath: noteFile.path,
        sourcePath: fileRecord.path,
        remoteUrl: fileRecord.remoteUrl,
        trashed: false,
        dueAt: new Date(dueAt).toISOString()
      });
    }
  }
  async deleteLocalFileRecords(noteFile, localFiles, status) {
    for (const fileRecord of localFiles) {
      const file = this.app.vault.getAbstractFileByPath(fileRecord.path);
      if (!(file instanceof import_obsidian5.TFile)) {
        this.addLog({
          status: `${status}-missing-local-file`,
          notePath: noteFile.path,
          sourcePath: fileRecord.path,
          remoteUrl: fileRecord.remoteUrl,
          trashed: false
        });
        continue;
      }
      await this.app.fileManager.trashFile(file);
      this.addLog({
        status,
        notePath: noteFile.path,
        sourcePath: fileRecord.path,
        remoteUrl: fileRecord.remoteUrl,
        trashed: true
      });
    }
    this.settings.pendingDeletes = (this.settings.pendingDeletes || []).filter(
      (entry) => !localFiles.some((f) => f.path === entry.sourcePath)
    );
    await this.saveSettings();
  }
  async processPendingDeletes() {
    const pending = Array.isArray(this.settings.pendingDeletes) ? this.settings.pendingDeletes : [];
    const now = Date.now();
    const due = pending.filter((entry) => Number(entry.dueAt) <= now);
    if (due.length === 0)
      return;
    const remaining = pending.filter((entry) => Number(entry.dueAt) > now);
    this.settings.pendingDeletes = remaining;
    for (const entry of due) {
      try {
        const noteFile = this.app.vault.getAbstractFileByPath(entry.notePath);
        await this.deleteLocalFileRecords(
          noteFile instanceof import_obsidian5.TFile ? noteFile : { path: entry.notePath },
          [{ path: entry.sourcePath, name: basename2(entry.sourcePath), remoteUrl: entry.remoteUrl }],
          "delayed-delete"
        );
      } catch (error) {
        console.error(`Delayed delete failed for ${entry.sourcePath}:`, error);
      }
    }
    await this.saveSettings();
  }
  ensureS3Settings() {
    const s3 = this.settings.s3;
    const missing = [];
    for (const key of [
      "endpoint",
      "bucketName",
      "accessKeyId",
      "secretAccessKey",
      "customDomainName"
    ]) {
      if (!String(s3[key] || "").trim())
        missing.push(key);
    }
    if (s3.provider !== "r2" && !String(s3.region || "").trim())
      missing.push("region");
    if (missing.length)
      throw new Error(this.t("missingS3", { settings: missing.join(", ") }));
  }
  addLog(entry) {
    this.settings.logs.unshift({
      time: (/* @__PURE__ */ new Date()).toISOString(),
      ...entry
    });
    this.settings.logs = this.settings.logs.slice(0, 100);
  }
};

// src/main.ts
var main_default = AttachmentImagebedManagerPlugin;
